# Generated by Django 5.1.4 on 2024-12-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarHire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_type',
            field=models.CharField(choices=[('1', 'premium'), ('2', 'deluxe'), ('3', 'regular')], max_length=50),
        ),
    ]
