# Generated by Django 5.1.4 on 2024-12-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarHire', '0002_alter_cars_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_type',
            field=models.CharField(choices=[('1', 'Toyota Harrier'), ('2', 'Toyota Surf'), ('3', 'Subaru Forester'), ('4', 'Subaru Outback'), ('5', 'Subaru Cross'), ('6', 'Subaru Impreza'), ('7', 'Nissan X-Trail'), ('8', 'Mazda CX-5'), ('9', 'Toyota RAV4'), ('10', 'Mitsubishi Pajero'), ('11', 'Mitsubishi Montero'), ('12', 'Mitsubishi Montero Sport'), ('13', 'Toyota Land Cruiser Prado'), ('14', 'Toyota Fortuner'), ('15', 'Nissan Patro'), ('16', 'Toyota RAV4 Avensis'), ('17', 'Toyota Highlander'), ('18', 'Nissan Altima'), ('19', 'Nissan Rogue'), ('20', 'Honda Civic'), ('21', 'Honda CR-V'), ('22', 'Ford Fusion'), ('23', 'Ford Mustang'), ('24', 'Ford Explorer'), ('25', 'Ford Focus'), ('26', 'Ford Fiesta'), ('27', 'Ford Edge'), ('28', 'Ford C-Max Hybrid'), ('29', 'Ford Mustang GT'), ('30', 'Ford Escape')], max_length=50),
        ),
    ]
